# Generated by Django 5.2.3 on 2025-07-04 14:48

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_materials", "0005_alter_lesson_course"),
        ("users", "0003_alter_user_date_joined_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "payment", "verbose_name_plural": "payments"},
        ),
        migrations.RemoveField(
            model_name="payment",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="type",
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("BANK_TRANSFER", "Банковский перевод"),
                    ("CASH", "Наличными"),
                ],
                default="BANK_TRANSFER",
                help_text="Выберите способ оплаты",
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="выберите пользователя",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Введите сумму платежа",
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Сумма платежа",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите курс",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="edu_materials.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите лекцию",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="edu_materials.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                help_text="Введите дату платежа",
                verbose_name="Дата оплаты",
            ),
        ),
    ]
