# Generated by Django 5.2.3 on 2025-07-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edu_materials", "0005_alter_lesson_course"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
